# **2k22/CSE/131**
# **Muhmmad Bilal Abid Rajput**

In [ ]:
import numpy as np

In [ ]:
my_arr = np.arange(1000)
my_list = np.arange(1000)

In [ ]:
data1 = [11,5.5,2,3.7,1.3,2.0]
array = np.array(data1,dtype = int)
print(array)
print(array.dtype)
print(array.shape)
print(array.ndim)

[11  5  2  3  1  2]
int64
(6,)
1


In [ ]:
data2 = [[1,3,5,7,9,11],[2,4,6,8,10,12]] # both lists must have same number of elements
array2 = np.array(data2, dtype = int)
print(array2.ndim)
print(array2.shape)
2

2
(2, 6)


2

In [ ]:
array3 = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
array3

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [ ]:
print(array3 * array3)

[[  1   9  25  49  81 121]
 [  4  16  36  64 100 144]]


In [ ]:
print(array3 - array3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
print(array3 **2)

[[  1   9  25  49  81 121]
 [  4  16  36  64 100 144]]


In [ ]:
print(array3 > array)

[[False False  True  True  True  True]
 [False False  True  True  True  True]]


In [ ]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr[4]

4

In [ ]:
arr[4:10]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr[5:12] = 15
arr

array([ 0,  1,  2,  3,  4, 15, 15, 15, 15, 15, 15, 15, 12, 13, 14])

In [ ]:
arr = np.arange(15)
arr_slice = arr[5:12]
arr_slice

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr_slice[5] = 1629
arr

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 1629,
         11,   12,   13,   14])

In [ ]:
arr2d = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12],[1,5,12,14,72,124000]])
arr2d[2]

array([     1,      5,     12,     14,     72, 124000])

In [ ]:
arr2d[1,3]

8

In [ ]:
for i in range(len(arr2d)):
    print(arr2d[i,5])

11
12
124000


In [ ]:
for i in range(-1,-3,-1):
    print(arr2d[1,i])

12
10


In [ ]:
arr0 = np.array([1])
arr0

array([1])

In [ ]:
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr3 = np.array([[1],[2],[3]])
arr3

array([[1],
       [2],
       [3]])

In [ ]:
arr4 = np.array([[5,0,0],[0,5,0],[0,0,5]])
arr4

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [ ]:
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr6 = np.array([[8,0,0],[0,4,0],[0,0,9]])
arr6

array([[8, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [ ]:
arr7 = np.array([[8,0,0],[6,4,0],[5,7,9]])
arr7

array([[8, 0, 0],
       [6, 4, 0],
       [5, 7, 9]])

In [ ]:
arr8 = np.array([[8,5,6],[0,4,7],[0,0,9]])
arr8

array([[8, 5, 6],
       [0, 4, 7],
       [0, 0, 9]])

In [ ]:
arr9 = np.array([[1,5],[9,8]])
arr9

array([[1, 5],
       [9, 8]])

In [ ]:
arr10 = np.array([[3,6,9],[6,12,18],[2,4,6]])
arr10

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 2,  4,  6]])

In [ ]:
arr11 = np.array([[2,1],[1,2]])
arr11

array([[2, 1],
       [1, 2]])

In [ ]:
arr12 = np.array([[1,0],[0,0]])
arr12

array([[1, 0],
       [0, 0]])

In [ ]:
arr13 = np.array([[0,3,5],[-3,0,-2],[-5,2,0]])
arr13

array([[ 0,  3,  5],
       [-3,  0, -2],
       [-5,  2,  0]])